CREATE TABLE IF NOT EXISTS SurveyTypes (
  id SERIAL PRIMARY KEY,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Surveys (
  id SERIAL PRIMARY KEY,
  summary VARCHAR(255) NOT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  survey_type_id INTEGER NOT NULL,
  FOREIGN KEY (survey_type_id) REFERENCES SurveyTypes (id)
);
