services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: survey_maker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/survey_maker_db -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db
volumes:
  db: